name: s3 bucket deployement

on|:
  push: 
    Branch:
        - a.yml

Jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    -name: sync state web
      run:
        aws s3 sync. s3://gulraizgulshan-task-by-zain

